### ISSUE TITLE
Incomplete Page Title

### ISSUE THREAD

**Issue by amitness** [okfnepal/election-nepal#36]
The page title for previewing data is incomplete: http://electionnepal.org/data-preview/46/

**| Election Nepal - Data Portal**

**Comment by sagargg** [comment]
we must change the link  with  title slugs instead of id.  currently there is no slug field  on the  dataset model.  If we created once , the older  data tables  also need to be update slug value.   i'm getting  trouble with generating  default slug relevant  to uploaded  dataset.  I think we have to update it manually for old dataset.

**Comment by nikeshbalami** [comment]
It this solves the issue, Let's create a space for Slugs. I will be updating it manually for old datasets too, cuz there aren't many till now.
