### ISSUE TITLE
Redirection and attribution

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal#6]
Redirect to home page while click on Election Nepal logo and attribution page for the background image used.

**Comment by studenton** [comment]
@sagargg I was trying to tackle this, but the code on the repo seems older than what's deployed on website. I don't get any navbar like on live site.

![screenshot from 2017-04-06 14 00 27](https://cloud.githubusercontent.com/assets/8587189/24744342/7615078e-1ad1-11e7-8c0e-ea1549e9db96.png)

and this

![error2](https://cloud.githubusercontent.com/assets/8587189/24744371/8c46fcf6-1ad1-11e7-94e6-ef07d06ada97.png)

**Comment by sagargg** [comment]
You just created new db.  Just goto the admin panel and add rich-text page.  Admin panel is accessible on /admin.  Otherwise it will throw  404.   
Same for other page. 
![screen shot 2017-04-06 at 2 52 01 pm](https://cloud.githubusercontent.com/assets/11631101/24746388/a51a9736-1ad8-11e7-9f0a-3f2a1a67fa80.png)

**Comment by studenton** [comment]
683bbf36236bac23358bd0ac99474a21d0f5aa04 fixes this issue partially. Now homepage will open on clicking logo.
